### ISSUE TITLE
St

### ISSUE THREAD

**Issue by thorsten-de** [my-flow/mt940#3]
Hey, I'm evaluating your FinTex library, and fetching my transactions, I was a bit surprised about whitespaces in the transactions purpose. One issue is, you pipe the content through `String.strip`. 

Compared with what I get in our legacy application, using C# and Subsemblys FinTs, some important whitspace is stripped. Btw, I looked into betterplace/mt940_parser, the content isn't stripped there. 

Is there a special purpose for using `String.strip`? I removed it and am quite happy with the result.

**Comment by my-flow** [comment]
@thorsten-de Good catch! I will remove the use of `String.strip` in the next release, so that the resulting `MT940.StatementLineInformation` will preserve all the whitespaces from the original input data.
